services:
  - type: web
    name: backend-restaurant-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 8080
